import { afterEach, describe, expect, mock, test } from 'bun:test'

const availableServices = [
  {
    id: 'service-1',
    name: 'Beach tour',
    category: 'Tour',
    price: 100000,
    originalPrice: 150000,
    vendorName: 'S-Loco Vendor',
  },
]

const query = {
  from() {
    return this
  },
  innerJoin() {
    return this
  },
  leftJoin() {
    return this
  },
  where() {
    return this
  },
  limit() {
    return availableServices
  },
}

mock.module('../src/db', () => ({
  getDb: () => ({
    select: () => query,
  }),
}))

const originalEnv = { ...process.env }
const originalFetch = globalThis.fetch

afterEach(() => {
  process.env = { ...originalEnv }
  globalThis.fetch = originalFetch
})

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })
}

describe('generateItinerary', () => {
  test('uses configured OpenAI-compatible endpoint and parses JSON content', async () => {
    const calls: Array<{ url: string; init: RequestInit }> = []
    process.env.OPENAI_API_KEY = 'test-key'
    process.env.OPENAI_BASE_URL = 'https://9router.test/v1'
    process.env.OPENAI_MODEL = 'gpt-5.5'
    delete process.env.GEMINI_API_KEY

    globalThis.fetch = async (url: string | URL | Request, init?: RequestInit) => {
      calls.push({ url: String(url), init: init ?? {} })
      return jsonResponse({
        choices: [
          {
            message: {
              content: JSON.stringify({
                title: 'Custom AI itinerary',
                summary: 'Generated by custom endpoint',
                days: [],
                total_estimated_cost: 123000,
                tips: ['Book early'],
              }),
            },
          },
        ],
      })
    }

    const { generateItinerary } = await import('../src/services/itinerary.service')
    const result = await generateItinerary({
      days: 1,
      budget: 123000,
      preferences: ['food'],
      groupType: 'couple',
    })

    expect(calls).toHaveLength(1)
    expect(calls[0]?.url).toBe('https://9router.test/v1/chat/completions')
    expect(calls[0]?.init.headers).toMatchObject({
      Authorization: 'Bearer test-key',
      'Content-Type': 'application/json',
    })

    const body = JSON.parse(String(calls[0]?.init.body))
    expect(body).toMatchObject({
      model: 'gpt-5.5',
      temperature: 0.7,
      max_tokens: 4096,
    })
    expect(body.messages[0]).toMatchObject({ role: 'user' })
    expect(result.title).toBe('Custom AI itinerary')
  })
})
