-- Migration: 0000_init.sql
-- S-Loco Phase 2 — Full schema (19 tables + enums + indexes)
-- Generated by DB Engineer agent (Phase 2)
-- 2026-04-03

BEGIN;

-- ═══════════════════════════════════════════════════════════════════
-- ENUMS
-- ═══════════════════════════════════════════════════════════════════

CREATE TYPE user_role AS ENUM ('tourist', 'vendor_owner', 'admin');

CREATE TYPE vendor_status AS ENUM ('pending', 'active', 'suspended');

CREATE TYPE settlement_type AS ENUM ('instant', 'periodic');

CREATE TYPE order_status AS ENUM ('created', 'paid', 'partially_refunded', 'refunded', 'cancelled');

CREATE TYPE voucher_status AS ENUM ('created', 'paid', 'redeemed', 'completed', 'settled', 'refunded', 'expired', 'cancelled');

CREATE TYPE payment_gateway AS ENUM ('vnpay', 'momo', 'sepay');

CREATE TYPE payment_status AS ENUM ('pending', 'success', 'failed', 'refunded');

CREATE TYPE settlement_status AS ENUM ('pending', 'approved', 'disbursed', 'rejected');

CREATE TYPE article_category AS ENUM ('news', 'event', 'guide');

-- ═══════════════════════════════════════════════════════════════════
-- USERS & AUTH
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE users (
  id              UUID        NOT NULL DEFAULT gen_random_uuid(),
  phone           VARCHAR(20),
  email           VARCHAR(255),
  full_name       VARCHAR(100),
  avatar_url      TEXT,
  role            user_role   NOT NULL DEFAULT 'tourist',
  password_hash   TEXT,
  is_active       BOOLEAN     NOT NULL DEFAULT true,
  fcm_token       TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX users_phone_idx ON users (phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX users_email_idx ON users (email) WHERE email IS NOT NULL;
CREATE INDEX users_role_idx ON users (role);
CREATE INDEX users_created_at_idx ON users (created_at);

COMMENT ON TABLE users IS 'Core user table — tourists, vendor owners, admins';
COMMENT ON COLUMN users.fcm_token IS 'Firebase Cloud Messaging token for push notifications';

CREATE TABLE user_sessions (
  id                UUID        NOT NULL DEFAULT gen_random_uuid(),
  user_id           UUID        NOT NULL,
  refresh_token_hash TEXT       NOT NULL,
  device_info       JSONB,
  ip_address        VARCHAR(45),
  expires_at        TIMESTAMPTZ NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX user_sessions_user_id_idx ON user_sessions (user_id);

CREATE TABLE otp_codes (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  phone       VARCHAR(20) NOT NULL,
  code        VARCHAR(10) NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  verified    BOOLEAN     NOT NULL DEFAULT false,
  attempts    INTEGER     NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE INDEX otp_codes_phone_expires_idx ON otp_codes (phone, expires_at);

-- ═══════════════════════════════════════════════════════════════════
-- VENDORS & SERVICES
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE service_categories (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  name        VARCHAR(100) NOT NULL,
  slug        VARCHAR(100) NOT NULL,
  icon        VARCHAR(100),
  sort_order  INTEGER     NOT NULL DEFAULT 0,
  is_active   BOOLEAN     NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX service_categories_slug_idx ON service_categories (slug);
CREATE INDEX service_categories_sort_order_idx ON service_categories (sort_order);

CREATE TABLE vendors (
  id                     UUID              NOT NULL DEFAULT gen_random_uuid(),
  owner_id               UUID              NOT NULL,
  name                   VARCHAR(200)      NOT NULL,
  slug                   VARCHAR(200)      NOT NULL,
  description            TEXT,
  logo_url               TEXT,
  cover_image_url        TEXT,
  address                TEXT,
  latitude               DECIMAL(10, 7),
  longitude              DECIMAL(10, 7),
  phone                  VARCHAR(20),
  email                  VARCHAR(255),
  status                 vendor_status      NOT NULL DEFAULT 'pending',
  settlement_type        settlement_type    NOT NULL DEFAULT 'periodic',
  settlement_period_days INTEGER           NOT NULL DEFAULT 3,
  commission_rate        DECIMAL(5, 2)     NOT NULL DEFAULT 8.00,
  rating_avg             DECIMAL(3, 2)     NOT NULL DEFAULT 0.00,
  rating_count           INTEGER           NOT NULL DEFAULT 0,
  review_count           INTEGER           NOT NULL DEFAULT 0,
  business_hours         JSONB,
  metadata               JSONB,
  rejection_reason       TEXT,
  created_at             TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  deleted_at             TIMESTAMPTZ,
  PRIMARY KEY (id),
  FOREIGN KEY (owner_id) REFERENCES users(id),
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX vendors_slug_idx ON vendors (slug);
CREATE INDEX vendors_owner_id_idx ON vendors (owner_id);
CREATE INDEX vendors_status_idx ON vendors (status);
CREATE INDEX vendors_status_created_at_idx ON vendors (status, created_at DESC);
CREATE INDEX vendors_deleted_at_idx ON vendors (deleted_at) WHERE deleted_at IS NULL;

COMMENT ON TABLE vendors IS 'Vendor/business entities — restaurants, hotels, spas, etc.';

CREATE TABLE services (
  id                    UUID          NOT NULL DEFAULT gen_random_uuid(),
  vendor_id             UUID          NOT NULL,
  category_id           UUID          NOT NULL,
  name                  VARCHAR(200)  NOT NULL,
  slug                  VARCHAR(200)  NOT NULL,
  description           TEXT,
  original_price        DECIMAL(12, 2) NOT NULL,
  discount_price        DECIMAL(12, 2),
  discount_percent      DECIMAL(5, 2),
  images                JSONB        DEFAULT '[]',
  options               JSONB,
  duration_minutes      INTEGER,
  max_quantity_per_order INTEGER     NOT NULL DEFAULT 10,
  is_active             BOOLEAN     NOT NULL DEFAULT true,
  sort_order            INTEGER     NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at            TIMESTAMPTZ,
  PRIMARY KEY (id),
  FOREIGN KEY (vendor_id) REFERENCES vendors(id),
  FOREIGN KEY (category_id) REFERENCES service_categories(id)
);
CREATE INDEX services_vendor_id_idx ON services (vendor_id);
CREATE INDEX services_category_id_idx ON services (category_id);
CREATE INDEX services_vendor_category_active_idx ON services (vendor_id, category_id)
  WHERE deleted_at IS NULL AND is_active = true;
CREATE INDEX services_deleted_at_idx ON services (deleted_at) WHERE deleted_at IS NULL;

-- ═══════════════════════════════════════════════════════════════════
-- COMBOS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE combos (
  id                UUID          NOT NULL DEFAULT gen_random_uuid(),
  vendor_id         UUID          NOT NULL,
  name              VARCHAR(200)  NOT NULL,
  slug              VARCHAR(200)  NOT NULL,
  description       TEXT,
  cover_image_url   TEXT,
  original_price    DECIMAL(12, 2) NOT NULL,
  combo_price       DECIMAL(12, 2) NOT NULL,
  discount_pct      DECIMAL(5, 2),
  valid_from        TIMESTAMPTZ,
  valid_to          TIMESTAMPTZ,
  max_quantity      INTEGER,
  is_active         BOOLEAN     NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (vendor_id) REFERENCES vendors(id)
);
CREATE INDEX combos_vendor_id_idx ON combos (vendor_id);
CREATE INDEX combos_valid_dates_idx ON combos (valid_from, valid_to) WHERE valid_from IS NOT NULL;

CREATE TABLE combo_items (
  id          UUID    NOT NULL DEFAULT gen_random_uuid(),
  combo_id    UUID    NOT NULL,
  service_id  UUID    NOT NULL,
  quantity    INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  FOREIGN KEY (combo_id) REFERENCES combos(id) ON DELETE CASCADE,
  FOREIGN KEY (service_id) REFERENCES services(id)
);
CREATE INDEX combo_items_combo_id_idx ON combo_items (combo_id);

-- ═══════════════════════════════════════════════════════════════════
-- ORDERS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE orders (
  id              UUID          NOT NULL DEFAULT gen_random_uuid(),
  order_number    VARCHAR(50)   NOT NULL,
  user_id         UUID          NOT NULL,
  total_amount    DECIMAL(12, 2) NOT NULL,
  discount_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  final_amount    DECIMAL(12, 2) NOT NULL,
  status          order_status   NOT NULL DEFAULT 'created',
  note            TEXT,
  metadata        JSONB,
  created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE UNIQUE INDEX orders_order_number_idx ON orders (order_number);
CREATE INDEX orders_user_id_created_at_idx ON orders (user_id, created_at DESC);
CREATE INDEX orders_status_idx ON orders (status);
CREATE INDEX orders_status_created_at_idx ON orders (status, created_at DESC);

COMMENT ON COLUMN orders.order_number IS 'Human-readable order number, e.g. SL-20260403-0001';
COMMENT ON TABLE orders IS 'Orders placed by tourists';

CREATE TABLE order_items (
  id              UUID          NOT NULL DEFAULT gen_random_uuid(),
  order_id        UUID          NOT NULL,
  service_id      UUID          NOT NULL,
  vendor_id       UUID          NOT NULL,
  combo_id        UUID,
  quantity        INTEGER       NOT NULL DEFAULT 1,
  unit_price      DECIMAL(12, 2) NOT NULL,
  total_price     DECIMAL(12, 2) NOT NULL,
  options         JSONB,
  service_snapshot JSONB        NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (order_id)  REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (service_id) REFERENCES services(id),
  FOREIGN KEY (vendor_id)  REFERENCES vendors(id),
  FOREIGN KEY (combo_id)   REFERENCES combos(id)
);
CREATE INDEX order_items_order_id_idx ON order_items (order_id);
CREATE INDEX order_items_vendor_id_idx ON order_items (vendor_id);

COMMENT ON COLUMN order_items.service_snapshot IS 'Frozen snapshot of service data at purchase time';

-- ═══════════════════════════════════════════════════════════════════
-- VOUCHERS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE vouchers (
  id              UUID             NOT NULL DEFAULT gen_random_uuid(),
  order_item_id   UUID             NOT NULL,
  user_id         UUID             NOT NULL,
  vendor_id       UUID             NOT NULL,
  service_id      UUID             NOT NULL,
  code            VARCHAR(20)      NOT NULL,
  qr_token        TEXT,
  status          voucher_status    NOT NULL DEFAULT 'created',
  amount          DECIMAL(12, 2),
  commission_amount DECIMAL(12, 2),
  redeemed_at     TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  settled_at      TIMESTAMPTZ,
  expires_at      TIMESTAMPTZ      NOT NULL,
  version         INTEGER          NOT NULL DEFAULT 1,
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (order_item_id) REFERENCES order_items(id),
  FOREIGN KEY (user_id)    REFERENCES users(id),
  FOREIGN KEY (vendor_id)  REFERENCES vendors(id),
  FOREIGN KEY (service_id) REFERENCES services(id)
);
CREATE UNIQUE INDEX vouchers_code_idx ON vouchers (code);
CREATE UNIQUE INDEX vouchers_qr_token_idx ON vouchers (qr_token) WHERE qr_token IS NOT NULL;
CREATE INDEX vouchers_user_id_created_at_idx ON vouchers (user_id, created_at DESC);
CREATE INDEX vouchers_vendor_id_status_created_at_idx ON vouchers (vendor_id, status, created_at DESC);
CREATE INDEX vouchers_status_created_at_idx ON vouchers (status, created_at DESC);
CREATE INDEX vouchers_user_id_status_paid_idx ON vouchers (user_id, status)
  WHERE status IN ('paid', 'redeemed');
CREATE INDEX vouchers_expires_at_idx ON vouchers (expires_at)
  WHERE status NOT IN ('settled', 'cancelled', 'expired');

COMMENT ON TABLE vouchers IS 'Electronic vouchers — the core S-Loco entity';
COMMENT ON COLUMN vouchers.qr_token IS 'Signed JWT token for QR code scanning';
COMMENT ON COLUMN vouchers.version IS 'Optimistic locking for concurrent redemption attempts';

-- ═══════════════════════════════════════════════════════════════════
-- PAYMENTS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE payments (
  id                      UUID             NOT NULL DEFAULT gen_random_uuid(),
  order_id                UUID             NOT NULL,
  gateway                 payment_gateway   NOT NULL,
  gateway_transaction_id  VARCHAR(255),
  amount                  DECIMAL(12, 2)    NOT NULL,
  status                  payment_status    NOT NULL DEFAULT 'pending',
  idempotency_key         VARCHAR(255)      NOT NULL,
  payment_url             TEXT,
  raw_webhook             JSONB,
  paid_at                 TIMESTAMPTZ,
  created_at              TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE UNIQUE INDEX payments_idempotency_key_idx ON payments (idempotency_key);
CREATE INDEX payments_order_id_idx ON payments (order_id);
CREATE INDEX payments_gateway_transaction_id_idx ON payments (gateway, gateway_transaction_id)
  WHERE gateway_transaction_id IS NOT NULL;

CREATE TABLE payment_events (
  id              UUID             NOT NULL DEFAULT gen_random_uuid(),
  gateway         payment_gateway   NOT NULL,
  idempotency_key VARCHAR(255)      NOT NULL,
  order_id        UUID,
  event_type      VARCHAR(100)      NOT NULL,
  payload         JSONB,
  processed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE UNIQUE INDEX payment_events_idempotency_key_idx ON payment_events (idempotency_key);
CREATE INDEX payment_events_gateway_idx ON payment_events (gateway);
CREATE INDEX payment_events_order_id_idx ON payment_events (order_id);

COMMENT ON TABLE payment_events IS 'Raw webhook event log for all payment gateway callbacks';

-- ═══════════════════════════════════════════════════════════════════
-- REFUNDS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE refunds (
  id                UUID             NOT NULL DEFAULT gen_random_uuid(),
  voucher_id        UUID             NOT NULL,
  payment_id        UUID             NOT NULL,
  amount            DECIMAL(12, 2)   NOT NULL,
  gateway           payment_gateway   NOT NULL,
  gateway_refund_id VARCHAR(255),
  status            VARCHAR(50)       NOT NULL DEFAULT 'pending',
  reason            TEXT,
  initiated_by      UUID,
  created_at        TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (voucher_id)  REFERENCES vouchers(id),
  FOREIGN KEY (payment_id)  REFERENCES payments(id),
  FOREIGN KEY (initiated_by) REFERENCES users(id)
);
CREATE INDEX refunds_voucher_id_idx ON refunds (voucher_id);
CREATE INDEX refunds_payment_id_idx ON refunds (payment_id);
CREATE INDEX refunds_status_idx ON refunds (status);

-- ═══════════════════════════════════════════════════════════════════
-- VOUCHER AUDIT LOG
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE voucher_audit_log (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  voucher_id  UUID        NOT NULL,
  from_status VARCHAR(50),
  to_status   VARCHAR(50) NOT NULL,
  actor_id    UUID,
  actor_type  VARCHAR(50),
  reason      TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (voucher_id) REFERENCES vouchers(id),
  FOREIGN KEY (actor_id)   REFERENCES users(id)
);
CREATE INDEX voucher_audit_log_voucher_id_created_at_idx ON voucher_audit_log (voucher_id, created_at DESC);
CREATE INDEX voucher_audit_log_created_at_idx ON voucher_audit_log (created_at DESC);

COMMENT ON TABLE voucher_audit_log IS 'Immutable audit trail for all voucher status transitions';

-- ═══════════════════════════════════════════════════════════════════
-- SETTLEMENTS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE settlements (
  id               UUID              NOT NULL DEFAULT gen_random_uuid(),
  vendor_id        UUID              NOT NULL,
  period_start     TIMESTAMPTZ       NOT NULL,
  period_end       TIMESTAMPTZ       NOT NULL,
  total_amount     DECIMAL(12, 2)    NOT NULL,
  commission_amount DECIMAL(12, 2)   NOT NULL,
  net_amount       DECIMAL(12, 2)    NOT NULL,
  voucher_count    INTEGER           NOT NULL DEFAULT 0,
  status           settlement_status  NOT NULL DEFAULT 'pending',
  approved_by      UUID,
  disbursed_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (vendor_id)  REFERENCES vendors(id),
  FOREIGN KEY (approved_by) REFERENCES users(id)
);
CREATE INDEX settlements_vendor_id_status_created_at_idx ON settlements (vendor_id, status, created_at DESC);
CREATE INDEX settlements_status_idx ON settlements (status);

CREATE TABLE settlement_items (
  id             UUID           NOT NULL DEFAULT gen_random_uuid(),
  settlement_id  UUID           NOT NULL,
  voucher_id     UUID           NOT NULL,
  amount         DECIMAL(12, 2) NOT NULL,
  commission     DECIMAL(12, 2) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE CASCADE,
  FOREIGN KEY (voucher_id)    REFERENCES vouchers(id)
);
CREATE INDEX settlement_items_settlement_id_idx ON settlement_items (settlement_id);

-- ═══════════════════════════════════════════════════════════════════
-- VENDOR QR SECRETS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE vendor_qr_secrets (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  vendor_id   UUID        NOT NULL,
  secret      TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (vendor_id) REFERENCES vendors(id)
);
CREATE INDEX vendor_qr_secrets_vendor_id_idx ON vendor_qr_secrets (vendor_id);

COMMENT ON TABLE vendor_qr_secrets IS 'HMAC secrets used to sign QR tokens for tourist self-redemption';

-- ═══════════════════════════════════════════════════════════════════
-- REVIEWS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE reviews (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL,
  vendor_id   UUID        NOT NULL,
  service_id  UUID,
  voucher_id  UUID,
  rating      INTEGER     NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment     TEXT,
  tags        TEXT[],
  is_visible  BOOLEAN    NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id)    REFERENCES users(id),
  FOREIGN KEY (vendor_id)  REFERENCES vendors(id),
  FOREIGN KEY (service_id) REFERENCES services(id),
  FOREIGN KEY (voucher_id) REFERENCES vouchers(id)
);
CREATE INDEX reviews_vendor_id_rating_created_at_idx ON reviews (vendor_id, rating, created_at DESC)
  WHERE deleted_at IS NULL AND is_visible = true;
CREATE INDEX reviews_user_id_idx ON reviews (user_id);
CREATE INDEX reviews_voucher_id_idx ON reviews (voucher_id) WHERE voucher_id IS NOT NULL;

-- ═══════════════════════════════════════════════════════════════════
-- ARTICLES
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE articles (
  id              UUID             NOT NULL DEFAULT gen_random_uuid(),
  title           VARCHAR(500)     NOT NULL,
  slug            VARCHAR(500)     NOT NULL,
  content         TEXT,
  cover_image_url TEXT,
  category        article_category  NOT NULL,
  is_featured     BOOLEAN          NOT NULL DEFAULT false,
  is_published    BOOLEAN          NOT NULL DEFAULT false,
  start_date      TIMESTAMPTZ,
  end_date        TIMESTAMPTZ,
  location        VARCHAR(500),
  published_at    TIMESTAMPTZ,
  author_id       UUID             NOT NULL,
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ,
  PRIMARY KEY (id),
  FOREIGN KEY (author_id) REFERENCES users(id)
);
CREATE UNIQUE INDEX articles_slug_idx ON articles (slug);
CREATE INDEX articles_category_published_at_idx ON articles (category, published_at DESC)
  WHERE deleted_at IS NULL AND is_published = true;
CREATE INDEX articles_is_featured_idx ON articles (is_featured) WHERE is_featured = true;

-- ═══════════════════════════════════════════════════════════════════
-- NOTIFICATIONS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE notifications (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL,
  type        VARCHAR(50) NOT NULL,
  title       VARCHAR(200) NOT NULL,
  body        TEXT        NOT NULL,
  payload     JSONB,
  is_read     BOOLEAN    NOT NULL DEFAULT false,
  read_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX notifications_user_id_created_at_idx ON notifications (user_id, created_at DESC);
CREATE INDEX notifications_user_id_is_read_idx ON notifications (user_id, is_read)
  WHERE is_read = false;
CREATE INDEX notifications_created_at_idx ON notifications (created_at DESC);

-- ═══════════════════════════════════════════════════════════════════
-- AUDIT LOGS
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE audit_logs (
  id          UUID        NOT NULL DEFAULT gen_random_uuid(),
  entity_type VARCHAR(50) NOT NULL,
  entity_id   UUID        NOT NULL,
  action      VARCHAR(50) NOT NULL,
  old_data    JSONB,
  new_data    JSONB,
  performed_by UUID,
  ip_address  VARCHAR(45),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (performed_by) REFERENCES users(id)
);
CREATE INDEX audit_logs_entity_type_entity_id_idx ON audit_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_logs_performed_by_idx ON audit_logs (performed_by);

-- ═══════════════════════════════════════════════════════════════════
-- HELPER FUNCTIONS & TRIGGERS
-- ═══════════════════════════════════════════════════════════════════

-- Auto-update updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to all tables that have the column
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER vendors_updated_at BEFORE UPDATE ON vendors
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER services_updated_at BEFORE UPDATE ON services
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER combos_updated_at BEFORE UPDATE ON combos
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER orders_updated_at BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER vouchers_updated_at BEFORE UPDATE ON vouchers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER payments_updated_at BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER settlements_updated_at BEFORE UPDATE ON settlements
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER reviews_updated_at BEFORE UPDATE ON reviews
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER articles_updated_at BEFORE UPDATE ON articles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ═══════════════════════════════════════════════════════════════════
-- VOUCHER STATUS TRANSITION GUARD
-- Valid transitions:
--   created  → paid, cancelled
--   paid     → redeemed, expired, refunded, cancelled
--   redeemed → completed
--   completed → settled
--   expired  → refunded
-- ═══════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION check_voucher_status_transition()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status = 'created' AND NEW.status NOT IN ('paid', 'cancelled') THEN
    RAISE EXCEPTION 'Invalid voucher transition: created → %', NEW.status;
  END IF;
  IF OLD.status = 'paid' AND NEW.status NOT IN ('redeemed', 'expired', 'refunded', 'cancelled') THEN
    RAISE EXCEPTION 'Invalid voucher transition: paid → %', NEW.status;
  END IF;
  IF OLD.status = 'redeemed' AND NEW.status NOT IN ('completed') THEN
    RAISE EXCEPTION 'Invalid voucher transition: redeemed → %', NEW.status;
  END IF;
  IF OLD.status = 'completed' AND NEW.status NOT IN ('settled') THEN
    RAISE EXCEPTION 'Invalid voucher transition: completed → %', NEW.status;
  END IF;
  IF OLD.status = 'expired' AND NEW.status NOT IN ('refunded') THEN
    RAISE EXCEPTION 'Invalid voucher transition: expired → %', NEW.status;
  END IF;
  -- settled, cancelled, refunded, expired are terminal — no transitions allowed
  IF OLD.status IN ('settled', 'cancelled', 'refunded') AND OLD.status != NEW.status THEN
    RAISE EXCEPTION 'Invalid voucher transition: % → % (terminal state)', OLD.status, NEW.status;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER voucher_status_transition
  AFTER UPDATE OF status ON vouchers
  FOR EACH ROW
  EXECUTE FUNCTION check_voucher_status_transition();

-- ═══════════════════════════════════════════════════════════════════
-- AUTO-SET paid_at ON payments status = 'success'
-- ═══════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION set_payment_paid_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'success' AND OLD.status != 'success' THEN
    NEW.paid_at = NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER payment_paid_at_trigger
  BEFORE UPDATE OF status ON payments
  FOR EACH ROW
  EXECUTE FUNCTION set_payment_paid_at();

COMMIT;
