-- Migration: 0003_saved_itineraries.sql
-- Add saved_itineraries table for AI itinerary save/share
-- Generated by Backend Developer agent (P2)

BEGIN;

CREATE TABLE saved_itineraries (
  id            UUID          NOT NULL DEFAULT gen_random_uuid(),
  user_id       UUID          NOT NULL,
  title         TEXT          NOT NULL,
  days          INTEGER      NOT NULL,
  budget        INTEGER      NOT NULL,
  preferences   JSONB,
  group_type    VARCHAR(50),
  result_json   JSONB        NOT NULL,
  is_shared     BOOLEAN      NOT NULL DEFAULT false,
  share_token   TEXT         UNIQUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX saved_itineraries_user_id_idx ON saved_itineraries (user_id);
CREATE UNIQUE INDEX saved_itineraries_share_token_idx ON saved_itineraries (share_token);

COMMIT;